services:
  marceen_saw.control.file_reader:
    class: Marceen\SAWBundle\Control\FileReader
    arguments: ['@kernel']

  marceen_saw.controller.import_controller:
    class: Marceen\SAWBundle\Controller\ImportController
    arguments: ['@marceen_saw.control.file_reader']
    calls:
          - [setContainer, ['@service_container']]